export const SUBJECTS = [
  'Álgebra',
  'Cálculo I',
  'Cálculo II',
  'Cálculo III',
  'Física I',
  'Física II',
  'Química General',
  'Programación I',
  'Programación II',
  'Estructuras de Datos',
  'Bases de Datos',
  'Algoritmos',
  'Sistemas Operativos',
  'Redes de Computadores',
  'Ingeniería de Software',
  'Estadística',
  'Probabilidad',
  'Investigación de Operaciones',
  'Contabilidad',
  'Economía',
  'Finanzas',
  'Marketing',
  'Administración',
  'Derecho Civil',
  'Derecho Penal',
  'Anatomía',
  'Fisiología',
  'Biología',
  'Microbiología',
  'Farmacología',
];

export const DAYS = [
  { value: 'monday', label: 'Lunes' },
  { value: 'tuesday', label: 'Martes' },
  { value: 'wednesday', label: 'Miércoles' },
  { value: 'thursday', label: 'Jueves' },
  { value: 'friday', label: 'Viernes' },
  { value: 'saturday', label: 'Sábado' },
  { value: 'sunday', label: 'Domingo' },
];

export const TIME_SLOTS = [
  '7:00 AM',
  '8:00 AM',
  '9:00 AM',
  '10:00 AM',
  '11:00 AM',
  '12:00 PM',
  '1:00 PM',
  '2:00 PM',
  '3:00 PM',
  '4:00 PM',
  '5:00 PM',
  '6:00 PM',
  '7:00 PM',
  '8:00 PM',
  '9:00 PM',
];

export const CAREERS = [
  'Ingeniería de Sistemas',
  'Ingeniería Informática',
  'Ingeniería de Software',
  'Ingeniería Industrial',
  'Ingeniería Civil',
  'Ingeniería Mecánica',
  'Ingeniería Eléctrica',
  'Ingeniería Electrónica',
  'Ingeniería Química',
  'Ingeniería Ambiental',
  'Ingeniería Biomédica',
  'Matemáticas',
  'Física',
  'Química',
  'Biología',
  'Medicina',
  'Enfermería',
  'Odontología',
  'Veterinaria',
  'Psicología',
  'Administración de Empresas',
  'Contaduría Pública',
  'Economía',
  'Finanzas',
  'Marketing',
  'Derecho',
  'Comunicación Social',
  'Periodismo',
  'Arquitectura',
  'Diseño Gráfico',
  'Pedagogía',
  'Educación',
  'Sociología',
  'Antropología',
  'Historia',
  'Literatura',
  'Lenguas Modernas',
  'Filosofía',
  'Teología',
];
